# Generated by Django 3.1 on 2020-08-16 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200816_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='cart_plant',
        ),
        migrations.CreateModel(
            name='UserCartPlant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.plant')),
            ],
        ),
    ]
